import Head from "next/head";
import { getSchedule } from "../data/schedule";
import styles from "../styles/Home.module.css";

import dynamic from "next/dynamic";
const Track = dynamic(() => import("../components/track"), { ssr: false });

export default function Home(props) {
  console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Track day="17" track="Summit Track" talks={props.talks} />
        <Track day="17" track="Base Camp Track" talks={props.talks} />
        <Track day="21" track="Summit Track" talks={props.talks} />
        <Track day="21" track="Base Camp Track" talks={props.talks} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const talks = await getSchedule();
  return {
    props: {
      talks,
    },
  };
}
