import Head from "next/head";
import Image from "next/image";
import { getSchedule } from "../data/schedule";
import styles from "../styles/Home.module.css";

function getDate(isoDate) {
  const date = new Date(isoDate);
  return date.toLocaleString();
}
export default function Home(props) {
  console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {props.talks.map((item, index) => (
          <div key={index}>
            {getDate(item.isoDate)} - {item.title}
          </div>
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const talks = await getSchedule();
  return {
    props: {
      talks,
    },
  };
}
