import Head from "next/head";
import { getSchedule } from "../data/schedule";

import dynamic from "next/dynamic";
const Track = dynamic(() => import("../components/track"), { ssr: false });

export default function Home(props) {
  console.log(props);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Track day="17" track="Summit Track" talks={props.talks} />
        <Track day="17" track="Base Camp Track" talks={props.talks} />
        <Track
          day="21"
          track="Summit Track"
          startTime="13:00"
          talks={props.talks}
        />
        <Track
          day="21"
          track="Base Camp Track"
          startTime="13:00"
          talks={props.talks}
        />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const talks = await getSchedule();
  return {
    props: {
      talks,
    },
  };
}
